version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 1

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    versioning-strategy: increase
    cooldown:
      default-days: 1
      exclude:
        - '@prettier/*'
        - '@standard-config/*'
        - prettier
        - prettier-plugin-expand-json
        - prettier-plugin-markdown-html
        - prettier-plugin-yaml
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - version-update:semver-major
