autoInstallPeers: false

color: always

gitChecks: false

minimumReleaseAgeExclude:
  - '@prettier/*'
  - '@standard-config/*'
  - prettier
  - prettier-plugin-expand-json
  - prettier-plugin-markdown-html
  - prettier-plugin-yaml

overrides:
  vite-plus>oxfmt: '-'

peerDependencyRules:
  allowAny:
    - '@vitest/coverage-v8'

strictPeerDependencies: true

trustPolicy: no-downgrade

updateConfig:
  ignoreDependencies:
    - '@types/node'
