autoInstallPeers: false

onlyBuiltDependencies:
  - esbuild

peerDependencyRules:
  allowedVersions:
    eslint: '*'
    vitest: '*'

strictPeerDependencies: true

updateConfig:
  ignoreDependencies:
    - '@types/node'
